//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFDMFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFDMFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyper Industries\\MFDMF\\.
        /// </summary>
        internal static string BaseDataDirectory {
            get {
                return ResourceManager.GetString("BaseDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Color {
            get {
                object obj = ResourceManager.GetObject("Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ConvergenceGrid {
            get {
                object obj = ResourceManager.GetObject("ConvergenceGrid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. The error has been logged..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTAS.
        /// </summary>
        internal static string HOTASKEY {
            get {
                return ResourceManager.GetString("HOTASKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IndianHead {
            get {
                object obj = ResourceManager.GetObject("IndianHead", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window is closed.
        /// </summary>
        internal static string MainWindowClosed {
            get {
                return ResourceManager.GetString("MainWindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window is closing.
        /// </summary>
        internal static string MainWindowClosing {
            get {
                return ResourceManager.GetString("MainWindowClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MaxRes {
            get {
                object obj = ResourceManager.GetObject("MaxRes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MFD {
            get {
                object obj = ResourceManager.GetObject("MFD", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the main window.
        /// </summary>
        internal static string StartingMain {
            get {
                return ResourceManager.GetString("StartingMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THROTTLE.
        /// </summary>
        internal static string THROTTLEKEY {
            get {
                return ResourceManager.GetString("THROTTLEKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TV {
            get {
                object obj = ResourceManager.GetObject("TV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested the main window be closed.
        /// </summary>
        internal static string UserRequestedAppClose {
            get {
                return ResourceManager.GetString("UserRequestedAppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested the cache be cleared.
        /// </summary>
        internal static string UserRequestedCacheClear {
            get {
                return ResourceManager.GetString("UserRequestedCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested the configuration be reloaded.
        /// </summary>
        internal static string UserRequestedReload {
            get {
                return ResourceManager.GetString("UserRequestedReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested the Test Pattern be displayed.
        /// </summary>
        internal static string UserRequestedTestPattern {
            get {
                return ResourceManager.GetString("UserRequestedTestPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window list has been cleared.
        /// </summary>
        internal static string WindowListCleared {
            get {
                return ResourceManager.GetString("WindowListCleared", resourceCulture);
            }
        }
    }
}
